#!/bin/python3

import os
import sys
import random

debug=False
id="idnotset"

#
# function definitions
#

def ERROR(*args, **kwargs):
    print("{}-{}: ERROR: ".format(sys.argv[0],id), *args, file=sys.stderr, flush=True, **kwargs)
    exit()

def DEBUG(*args, **kwargs):
    if debug:
        print("{}-{}: DEBUG: ".format(sys.argv[0],id), *args, file=sys.stderr, flush=True, **kwargs)

def chance(percent):
    return random.randint(0,99) < percent

#
# parse command line
#

if len(sys.argv) != 2:
    ERROR("len(sys.argv) = ", len(sys.argv))

id=sys.argv[1]
if id != "0" and id != "1":
    ERROR("expected 0 or 1 on cmdline")

#
# runtime loop
#

random.seed(0)
test_attack = True

while True:
    cmd = input().split()
    DEBUG("RECEIVED", cmd)

    if len(cmd) == 0:
        ERROR("blank line")

    if cmd[0] == "YESTERDAY_YOUR_OPPONENT":
        yesterday_opponent_attacked = (cmd[1] == "ATTACK")

    elif cmd[0] == "WHAT_WILL_YOU_DO_TODAY?":
        if yesterday_opponent_attacked:
            test_attack = False
        elif test_attack:
            pass
        else:
            test_attack = chance(10)

        if test_attack:
            print("ATTACK")
        else:
            print("ATTACK" if (yesterday_opponent_attacked and chance(90)) else "DEFEND")

    elif cmd[0] == "TERM":
        exit()

    else:
        ERROR("unexpected cmd", cmd[0])

