#!/bin/bash

ERROR() {
  echo "$player-$id: ERROR: $@" 1>&2
  exit
}

DEBUG() {
  if [ "$debug" = 1 ]; then
    echo "$player-$id: DEBUG: $@" 1>&2
  fi
}

player=$0
id=$1
debug=0
cycle=0

DEBUG "STARTING id=$id"

while [ 1 = 1 ]; do
  cycle=$((cycle + 1))
  read cmd arg
  DEBUG "$cmd $arg"
  if [ "$cmd" = "YESTERDAY_YOUR_OPPONENT" ]; then
    if [ "$arg" != ATTACK -a "$arg" != DEFEND ]; then
      ERROR "YESTERDAY_YOUR_OPPONENT invalid arg: '$arg'"
    fi
  elif [ "$cmd" = "WHAT_WILL_YOU_DO_TODAY?" ]; then
    echo DEFEND
  elif [ "$cmd" = TERM ]; then
    exit 0
  else  
    ERROR "INVALID_CMD $cmd"
  fi
done
