#!/bin/bash

# ARGS 
# - arg1: id - useful only for debug prints
#
# DEBUG PRINTS
# - direct debug prints to stderr
#
# INPUTS
# - GO 
# - GO ATTACK
# - GO PASSIVE
# - TERM
#
# OUTPUTS
# - ATTACK
# - PASSIVE

dbgpr() {
  if [ "$debug" = 1 ]; then
    echo "DBGPR: $player $id: $@" 1>&2
  fi
}

player=$0
id=$1
debug=0
cycle=0

dbgpr STARTING

while [ 1 = 1 ]; do
  cycle=$((cycle + 1))
  read cmd other_player_last_action
  if [ "$cmd" = GO ]; then
    dbgpr GO cycle=$cycle  other_player_last_action=$other_player_last_action
    echo ATTACK
  elif [ "$cmd" = TERM ]; then
    dbgpr TERM
    exit 0
  else  
    dbgpr "INVALID_CMD $cmd"
    exit 1
  fi
done
