#!/bin/python

# XXX put pgm names in the files

import os
import sys

debug=False
id="idnotset"

#
# function definitions
#

def ERROR(*args, **kwargs):
    print("{}-{}: ERROR: ".format(sys.argv[0],id), *args, file=sys.stderr, flush=True, **kwargs)
    exit()

def DEBUG(*args, **kwargs):
    if debug:
        print("{}-{}: DEBUG: ".format(sys.argv[0],id), *args, file=sys.stderr, flush=True, **kwargs)

#
# parse command line
#

if len(sys.argv) != 2:
    ERROR("len(sys.argv) = ", len(sys.argv))

id=sys.argv[1]
if id != "0" and id != "1":
    ERROR("expected 0 or 1 on cmdline")

#
# runtime loop
#

massive_retaliatory_strike = False

while True:
    cmd = input().split()
    DEBUG("RECEIVED", cmd)

    if len(cmd) == 0:
        ERROR("blank line")

    if cmd[0] == "YESTERDAY_YOUR_OPPONENT":
        if cmd[1] == "ATTACK":
            massive_retaliatory_strike = True
    elif cmd[0] == "WHAT_WILL_YOU_DO_TODAY?":
        if massive_retaliatory_strike:
            print("ATTACK", flush=True)
        else:
            print("DEFEND", flush=True)
    elif cmd[0] == "TERM":
        exit()
    else:
        ERROR("unexpected cmd", cmd[0])

